apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "expresscart.fullname" . }}
  labels:
{{ include "expresscart.labels" . | indent 4 }} 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "expresscart.fullname" . }}
    labels:
{{ include "expresscart.labels" . | indent 4 }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Value
        averageValue: 8m

