{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "expresscart.serviceAccountName" . }}
  labels:
{{ include "expresscart.labels" . | indent 4 }}
{{- end -}}
